In [2]:
import numpy as np

In [3]:
print(np.__version__)

2.1.3


In [77]:
a=np.array([32,43,54,65,21])
b=np.array([12,34,54,76,54])
print(a+b)

[ 44  77 108 141  75]


In [79]:
# array is a collection of data type
# it is three type 1d,2d,3d

In [81]:
a=np.array([1,2,3,4,5])
print('add',a+10)
print('sub',a-10)
print('multyple',a*10)
print('square',a**2)

add [11 12 13 14 15]
sub [-9 -8 -7 -6 -5]
multyple [10 20 30 40 50]
square [ 1  4  9 16 25]


In [84]:
b=([23,56,76,87])
print(np.sum(b))

242


In [86]:
print(np.shape(b))

(4,)


In [87]:
print(np.size(b))

4


In [88]:
print(np.ndim(b))

1


In [100]:
zero=np.zeros(1)
print(zero)

[0.]


In [105]:
zero=np.zeros((2,4))
print(zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [103]:
one=np.ones(1)
print(one)

[1.]


In [106]:
one=np.ones((2,5))
print(one)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [108]:
full=np.full((2,4),4)
print(full)

[[4 4 4 4]
 [4 4 4 4]]


In [109]:
arr=np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


In [114]:
arr=np.linspace(1,2,5)
print(arr)

[1.   1.25 1.5  1.75 2.  ]


In [123]:
a=np.arange(1,13)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [124]:
abc=a.reshape(3,4)
print(abc)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [126]:
data=np.array([21,34,54,54])
print(data[1])

34


In [127]:
data=np.array([[21,43,32],
             [23,54,34]])
print(data)

[[21 43 32]
 [23 54 34]]


In [143]:
arr = np.array([10, 20, 30, 40])

print('sum',np.sum(arr))
print('avg',np.mean(arr))
print('max',np.max(arr))
print('min',np.min(arr))
print('sqr',np.sqrt(arr))


sum 100
avg 25.0
max 40
min 10
sqr [3.16227766 4.47213595 5.47722558 6.32455532]


In [144]:
score = np.array([40, 60, 80, 90])
remark=score>55
print(remark)

[False  True  True  True]


In [145]:
score = np.array([40, 60, 80, 90])
remark=score[score>55]
print(remark)

[60 80 90]


In [148]:
score = np.array([40, 60, 80, 90])
remark=np.where(score>55,"can play","not")
print(score)
print(remark)

[40 60 80 90]
['not' 'can play' 'can play' 'can play']


In [150]:
number=np.array([12,43,54,6,5,54,3,231,2,24,3,5,65,67,54,34,23,43])
remark=np.where(number>=33,'pass','fail')
print(remark)

['fail' 'pass' 'pass' 'fail' 'fail' 'pass' 'fail' 'pass' 'fail' 'fail'
 'fail' 'fail' 'pass' 'pass' 'pass' 'pass' 'fail' 'pass']


In [151]:
number=np.array([12,43,54,6,5,54,3,231,2,24,3,5,65,67,54,34,23,43])
Pass=number[number>33]
print(Pass)

[ 43  54  54 231  65  67  54  34  43]


In [152]:
# exersice
# data = np.array([10, 25, 30, 45, 50])

# 1️⃣ Even numbers nikalo  
# 2️⃣ Mean nikalo  
# 3️⃣ data ko 5×1 me reshape karo  


In [159]:
data = np.array([10, 25, 30, 45, 50])
even=data[data%2!=0]
print(even)

[25 45]


In [160]:
data = np.array([10, 25, 30, 45, 50])
print(np.mean(data))

32.0


In [ ]:
reshape=reshape